### ISSUE TITLE
FEATURE REQUEST | Customize song info display and etc

### ISSUE THREAD

**Issue by pb29** [N0chteil-Productions/Apple-Music-RPC#2]
**Is your feature request related to a problem? Please describe.**
I want to display the song info just like this. don't need album title!

**Apple Music**
Song Title
Artist Name
02:52 Remaining

**Describe the solution you'd like**
feature that customize Album Title, Song Title, Artist Name display.

+ this is the finest Discord RPC thing of Windows version of iTunes I ever discovered! please keep it up!

**Comment by N0chteil** [comment]
Thank you for the suggestion and your positive feedback! We'll add this feature in the next update.

**Comment by N0chteil** [comment]
[New release](https://github.com/N0chteil-Productions/Apple-Music-RPC/releases/tag/v.2.2.5)

**Comment by pb29** [comment]
Just tested it out! works great, thanks!
